### PR TITLE
Associate

### PR DESCRIPTION
**Pull request by caacree**
PR to associate trails and hydrants. Seems to work pretty well; on Beaver Creek, had 1095 direct matches (inside the trail polygon) and 238 matched by the closest trail. 33 trails out of 46 had the same number of hydrants (I'm assuming they are all the correct hydrants, didn't go through and check), and only 4 trails were off by at least 3 hydrants. 

I might do something to highlight features that were done by the closest method instead of direct match later, but this is pretty much the desired functionality I think. I'll clean up the Dialog presentation a bit soon. 

Also, a TODO is to take care of overlapping trail polygons; I'm pretty sure they represent holes in the polygon (donut style) where there are a few trees or similar, but right now it sees them as overlapping trails of the same name, which is why there were a few multiple matches in my associate function. Also for showing them correctly on the map, they should be holes, not darker sections because of two trails there. Not a dealbreaker, but slightly off.

### CODE REVIEW

**Comment by caacree** [comment]
So geocoder is working too now, I just built with it after doing a fresh `npm install`, which gets everything. Not sure what it was, but some dependency issue where calling a general install does a more comprehensive fetch of whatever is needed to build it seems to be the case.

**Comment by caacree** [comment]
And now you can ignore what I wrote earlier about overlapping trail polygons, took care of those in the last commit as well. There might be an issue with his existing KML's when we export there; we're removing them as separate features and marking them as linearRings on the larger polygon, aka holes in it. But it looks pretty and works well on our maps for now.

**Comment by jolavb** [comment]
Hell of a PR we have here. Lookin forward to pulling this down. Code looks good to me.

**Comment by caacree** [comment]
The only real new stuff is `convertTrailFeaturesToDonuts` in mapUtils (open to better naming...) and the `AutoAssociate` component. The rest is cause I removed the data files which shouldn't be here and rebuilt mostly, with a few bits sprinkled around to make the donuts register as non-separate features in Import/Export and the TrailModify functions.

**Comment by jolavb** [comment]
Either way, 2 cool new features. Let's merge it.

**Pull request merged**
